env:
  browser: false
  commonjs: true
  es2021: true
extends: [ './es6/index' ]
parserOptions:
  ecmaVersion: 12
globals:
  test: readonly
  expect: readonly
ignorePatterns: [ "**/__fixtures__/**", "temp/**" ]