env:
  browser: true
  commonjs: true
  es2021: true
extends: [ './node/index' ]
parserOptions:
  ecmaVersion: 12
rules:
  import/no-commonjs: 0
globals:
  test: readonly
  expect: readonly
ignorePatterns: [ "**/__fixtures__/**" ]